### ISSUE TITLE
owner and license

### ISSUE THREAD

**Issue by ricardogando** [desihub/qlf-ui#9]
@weaverba137, @felipelm has just transferred this repository to desihub and lost owner privileges over it. It seems we cannot setup the license without it. Could you give @felipelm @crisingulani @campisano and myself owner power over this repo? Thanks,
Ricardo

**Comment by weaverba137** [comment]
The DESI team now has write access to the repository.  @felipelm already has write access.  But really, everyone should be part of the DESI team, and if not, we need to get them on the team.  Is @crisingulani registered as a DESI collaborator?  It looks like everyone else is.

**Comment by weaverba137** [comment]
According to GitHub, @felipelm already has write access.  See https://github.com/desihub/qlf-ui/settings/collaboration

In order to assist further, I would need to see the specific commands that are failing, error messages, etc.

**Comment by felipelm** [comment]
@weaverba137 it shows me error 404 (Page not found) when I try to access  https://github.com/desihub/qlf-ui/settings/collaboration.

**Comment by weaverba137** [comment]
That's not what I meant.  What are the specific commands that are failing, error messages, etc. when trying to modify the license file?

**Comment by felipelm** [comment]
@weaverba137 I added the license and I also want to fix the coverage webhook that broke after I transfer the repo but I can't see the settings.

**Comment by weaverba137** [comment]
OK, try again now.
